### ISSUE TITLE
Ultima linha não printa probabilidades

### ISSUE THREAD

**Issue by leonardocutrimamorim** [meloluan/Estudo_Lotofacil#5]
Luan, 

quando tento printar a ultima linha (onde mostra os jogos pro Concurso atual), o programa apenas printa o quadro de ###, porém não printa as probabilidades nem as dezenas.

Tentei JupyterLab e Notebook e nada nos dois.

Sabes a solução?

E parabéns pelo projeto! Bastante interessante!

**Comment by meloluan** [comment]
Fala @leonardocutrimamorim , tudo bem? Realmente essa última versão está com problemas para printar a probabilidade no final.

Havia refeito essa parte, pois os valores não estavam muito coerentes e não cheguei a finalizar.

Pretendo voltar a mexer nesse projeto e resolver esse problema.

Abraço e obrigado!
